package com.example.roots.repository

import com.example.roots.model.Inmueble
import com.example.roots.model.TipoInmueble
import com.example.roots.model.TipoPublicacion

object MockInmuebles {
    val sample = listOf(
        Inmueble(
            id = 1,
            direccion = "Cra 50 #20-30",
            precio = 350_000_000f,
            estrato = 4,
            numBanos = 2,
            numParqueaderos = 2,
            numHabitaciones = 3,
            metrosCuadrados = 85f,
            barrio = "La Castellana",
            ciudad = "Bogotá",
            descripcion = "Apartamento amplio con buena iluminación",
            fotos = listOf("inmueble1.jpg", "inmueble3.jpg", "inmueble6.jpg"),
            tipoPublicacion = TipoPublicacion.Venta,
            tipoInmueble = TipoInmueble.Apartamento,
            numFavoritos = 0,
            mensualidadAdministracion = 150_000f,
            antiguedad = 8,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.654321,
            longitud = -74.056789
        ),
        Inmueble(
            id = 2,
            direccion = "Cl 85 #15-10, Bogotá",
            precio = 450_000_000f,
            estrato = 5,
            numBanos = 3,
            numParqueaderos = 1,
            numHabitaciones = 4,
            metrosCuadrados = 120f,
            barrio = "El Country",
            ciudad = "Bogotá",
            descripcion = "Penthouse con terraza",
            fotos = listOf("inmueble2.jpg", "inmueble4.jpg", "inmueble6.jpg"),
            tipoPublicacion = TipoPublicacion.Venta,
            tipoInmueble = TipoInmueble.Penthouse,
            numFavoritos = 0,
            mensualidadAdministracion = 250_000f,
            antiguedad = 18,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.679012,
            longitud = -74.073456
        ),
        Inmueble(
            id = 3,
            direccion = "Cra 7 #112-25",
            precio = 480_000_000f,
            estrato = 5,
            numBanos = 2,
            numParqueaderos = 1,
            numHabitaciones = 3,
            metrosCuadrados = 95f,
            barrio = "Usaquén",
            ciudad = "Bogotá",
            descripcion = "Apartamento luminoso con balcón y vista al parque.",
            fotos = listOf("inmueble2.jpg", "inmueble6.jpg", "inmueble1.jpg"),
            tipoPublicacion = TipoPublicacion.Venta,
            tipoInmueble = TipoInmueble.Apartamento,
            numFavoritos = 4,
            mensualidadAdministracion = 220_000f,
            antiguedad = 1,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.7195,
            longitud = -74.0383
        ),
        Inmueble(
            id = 4,
            direccion = "Cl 85 #20-50",
            precio = 3_200_000f,
            estrato = 4,
            numBanos = 1,
            numParqueaderos = 3,
            numHabitaciones = 1,
            metrosCuadrados = 42f,
            barrio = "Chapinero",
            ciudad = "Bogotá",
            descripcion = "Apartaestudio moderno en zona gastronómica.",
            fotos = listOf("inmueble1.jpg", "inmueble2.jpg", "inmueble3.jpg"),
            tipoPublicacion = TipoPublicacion.Arriendo,
            tipoInmueble = TipoInmueble.Apartaestudio,
            numFavoritos = 7,
            mensualidadAdministracion = 180_000f,
            antiguedad = 28,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.6644,
            longitud = -74.0554
        ),
        Inmueble(
            id = 5,
            direccion = "Av El Dorado #30-15",
            precio = 650_000_000f,
            estrato = 3,
            numBanos = 2,
            numParqueaderos = 1,
            numHabitaciones = 2,
            metrosCuadrados = 78f,
            barrio = "Teusaquillo",
            ciudad = "Bogotá",
            descripcion = "Cómodo dúplex cerca de la zona universitaria.",
            fotos = listOf("inmueble4.jpg", "inmueble5.jpg", "inmueble6.jpg"),
            tipoPublicacion = TipoPublicacion.Venta,
            tipoInmueble = TipoInmueble.Casa,
            numFavoritos = 2,
            mensualidadAdministracion = 0f,
            antiguedad = 8,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.6374,
            longitud = -74.0895
        ),
        Inmueble(
            id = 6,
            direccion = "Cll 140 #10-20",
            precio = 250_000_000f,
            estrato = 3,
            numBanos = 1,
            numParqueaderos = 1,
            numHabitaciones = 2,
            metrosCuadrados = 60f,
            barrio = "Suba",
            ciudad = "Bogotá",
            descripcion = "Local comercial en sector residencial, alto tránsito.",
            fotos = listOf("inmueble1.jpg", "inmueble4.jpg", "inmueble5.jpg"),
            tipoPublicacion = TipoPublicacion.Venta,
            tipoInmueble = TipoInmueble.LocalComercial,
            numFavoritos = 5,
            mensualidadAdministracion = 150_000f,
            antiguedad = 20,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.7450,
            longitud = -74.0931
        ),
        Inmueble(
            id = 7,
            direccion = "Av de Las Américas #68-40",
            precio = 1_800_000f,
            estrato = 2,
            numBanos = 1,
            numParqueaderos = 0,
            numHabitaciones = 1,
            metrosCuadrados = 35f,
            barrio = "Kennedy",
            ciudad = "Bogotá",
            descripcion = "Habitación amoblada en casa familiar, ideal para estudiantes.",
            fotos = listOf("inmueble4.jpg", "inmueble3.jpg", "inmueble2.jpg"),
            tipoPublicacion = TipoPublicacion.Arriendo,
            tipoInmueble = TipoInmueble.Apartamento,
            numFavoritos = 10,
            mensualidadAdministracion = 100_000f,
            antiguedad = 15,
            fechaPublicacion = System.currentTimeMillis(),
            latitud = 4.6147,
            longitud = -74.1450
        )
    )
}
